version: '3'

services:
  api:
    build: ./packages/api
    image: ctf-api
    container_name: api
    ports:
      - '4000:4000'
    depends_on:
      - db
    restart: always
  db:
    image: 'postgres'
    container_name: db
    env_file:
      - packages/db/env
    expose:
      - '5432'
    restart: always
